# Generated by Django 5.2.3 on 2025-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Schedule news to be published at this time.', null=True),
        ),
    ]
